### ISSUE TITLE
Documentation Request: Migration Guide

### ISSUE THREAD

**Issue by gdevenyi** [dsh2dsh/zrepl#3]
I'm impressed by the additional features merged and I'd like to migrate my current setup, however I can't be sure there's no gotchas swapping in this version.

Would you please provide some basic details about this?

**Comment by dsh2dsh** [comment]
Hi,

sorry, I didn't get a notification about this issue. I found I wasn't subscribed to notifications and now I changed it.

Basically I'm not expecting any gotchas, because everything I changed, I changed with backward compatibility in mind. I expect everything should work with your current `zrepl.yaml`. Please let me know if you'll find some backward incompatibility.

**Comment by dsh2dsh** [comment]
Feedback timeout.
